---
name: Proc-SetUser
version: v0.1
author:
  - 'Dylan Martin <dmartin@sccd.ctc.edu>'
abstract: carefully drop root privileges
license: restrictive
requires:
  Test::More: 0
  version: 0
provides:
  Proc::SetUser:
    file: lib/Proc/SetUser.pm
    version: v0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
